CREATE TABLE T_USERS (
    ID NUMBER(10) PRIMARY KEY,
    FIRST_NAME VARCHAR2(50) NOT NULL
);

CREATE VIEW V_USERS AS
    SELECT ID, FIRST_NAME
    FROM T_USERS
    WITH CHECK OPTION;

CREATE SEQUENCE USER_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

INSERT INTO V_USERS (ID, FIRST_NAME) VALUES (USER_ID_SEQ.nextval, 'Beata');
INSERT INTO V_USERS (ID, FIRST_NAME) VALUES (USER_ID_SEQ.nextval, 'Łukasz');
INSERT INTO V_USERS (ID, FIRST_NAME) VALUES (USER_ID_SEQ.nextval, 'Rafał');