CREATE TABLE T_CLEANINGS (
    ID NUMBER(10) PRIMARY KEY,
    CLEANING_DATE TIMESTAMP NOT NULL,
    USER_ID NUMBER(10),
    FOREIGN KEY (USER_ID) REFERENCES T_USERS(ID)
);

CREATE VIEW V_CLEANINGS AS
    SELECT ID, CLEANING_DATE, USER_ID
    FROM T_CLEANINGS
    WITH CHECK OPTION;

CREATE SEQUENCE CLEANING_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;