spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: 'org.hibernate.dialect.OracleDialect'
    show-sql: true
  datasource:
    url: 'jdbc:oracle:thin:@192.168.0.28521/ORCLCDB'
    username: 'dummy'
    password: 'dummy'
    driver-class-name: oracle.jdbc.driver.OracleDriver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  flyway:
    baseline-on-migrate: true
  output:
    ansi:
      enabled: ALWAYS
server:
  address: '0.0.0.0'
  port: 8083